In [1]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Define network parameters
input_neurons = 2
hidden_neurons = 4
output_neurons = 1
learning_rate = 0.1
epochs = 10000

# Define training data (XOR problem)
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

Y = np.array([[0], 
              [1], 
              [1], 
              [0]])

# Initialize weights and biases (no *0.01, better random spread)
W1 = np.random.randn(input_neurons, hidden_neurons)
b1 = np.random.randn(1, hidden_neurons)
W2 = np.random.randn(hidden_neurons, output_neurons)
b2 = np.random.randn(1, output_neurons)

# Define sigmoid and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training the network
for epoch in range(epochs):
    # Forward pass
    hidden_layer_input = np.dot(X, W1) + b1
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, W2) + b2
    predicted_output = sigmoid(output_layer_input)

    # Backward pass (Backpropagation)
    output_error = Y - predicted_output
    output_delta = output_error * sigmoid_derivative(predicted_output)

    hidden_error = output_delta.dot(W2.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    W2 += hidden_layer_output.T.dot(output_delta) * learning_rate
    b2 += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
    W1 += X.T.dot(hidden_delta) * learning_rate
    b1 += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate

# Testing the network
x_test = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

hidden_layer_input = np.dot(x_test, W1) + b1
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output, W2) + b2
output_layer_output = sigmoid(output_layer_input)

# Printing results
print("Input:")
print(x_test)

print("\nPredicted Output (Approximate values):")
print(np.round(output_layer_output, 4))  # Rounded to 4 decimal places

print("\nExpected Output:")
print(Y)


Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Predicted Output (Approximate values):
[[0.0335]
 [0.9593]
 [0.9607]
 [0.0456]]

Expected Output:
[[0]
 [1]
 [1]
 [0]]
